Add support for cancel-able downloads
bioimage-io/spec-bioimage-io pull request #466
Opened 2022-07-06 14:00 UTC by k-dominik

Hi @FynnBe,

we talked about this a while ago. Main motivation is being able to support progress reporting other than in the cmd and immediate cancellation of long running downloads. All is done via a `pbar` that is passed through the functions until it reaches `_download_url`.

2022-07-08 08:34 UTC, FynnBe requested changes
pbar needs to be handed down in recursive `resolve_source` calls. otherwise this looks very good! 👍

2022-07-08 08:34 UTC, FynnBe commented on bioimageio/spec/shared/_resolve_source.py
> +        source: resource description as path, or uri
a url to a weight file would not be a 'resource description' as in resource description file (RDF)... Of course it is not wrong to call it that, but I find this confusing
```suggestion
        source: e.g. a path or uri
```

2022-07-08 08:34 UTC, FynnBe commented on bioimageio/spec/shared/_resolve_source.py
> +          (by raising CancelledError).
```suggestion
          (by raising DownloadCancelled).
```

2022-07-08 08:34 UTC, FynnBe commented on bioimageio/spec/shared/_resolve_source.py
>      return resolve_source(fields.Union([fields.URI(), fields.Path()]).deserialize(source), root_path, output)
```suggestion
    return resolve_source(fields.Union([fields.URI(), fields.Path()]).deserialize(source), root_path, output, pbar)
```

2022-07-08 08:34 UTC, FynnBe commented on bioimageio/spec/shared/_resolve_source.py
> +class DownloadCancelled(Exception):
as this is a private model, maybe we should move `DownloadCancelled` to `common`?

2022-07-08 08:34 UTC, FynnBe commented on bioimageio/spec/shared/_resolve_source.py
>          callable_name=source.callable_name, source_file=resolve_source(source.source_file, root_path, output)
```suggestion
        callable_name=source.callable_name, source_file=resolve_source(source.source_file, root_path, output, pbar)
```

2022-07-08 08:34 UTC, FynnBe commented on bioimageio/spec/shared/_resolve_source.py
>          callable_name=source.callable_name, source_file=resolve_source(source.source_file, root_path, output)
```suggestion
        callable_name=source.callable_name, source_file=resolve_source(source.source_file, root_path, output, pbar)
```

2022-07-08 08:34 UTC, FynnBe commented on bioimageio/spec/shared/_resolve_source.py
>      return [resolve_source(el, root_path, out) for el, out in zip(source, output or [None] * len(source))]
```suggestion
    assert pbar is None or len(pbar) == len(source)
    return [resolve_source(el, root_path, out, pb) for el, out, pb in zip(source, output or [None] * len(source), pbar)]
```

2022-07-08 08:34 UTC, FynnBe commented on bioimageio/spec/shared/_resolve_source.py
> +    pbar=None,
```suggestion
    pbar: typing.Sequence = None,
```

2022-07-19 08:56 UTC, k-dominik commented
thx @FynnBe for the review! I even found one more invocation of `resolve_source` that needed the `pbar` treatment.

2022-07-21 08:34 UTC, FynnBe commented on bioimageio/spec/shared/_resolve_source.py
> +class DownloadCancelled(Exception):
We can move later then when needed. I didn't see that it was available in shared.

2022-07-21 08:35 UTC, merged